name: slip_0010_ed25519
version: 3.0.0

description: BIP-0032 like derivation for ed25519 curve
repository: https://github.com/Eucalyptus-Labs/dart-ed25519-hd-key

environment:
  sdk: '>=2.18.4 <=3.0.0'

dependencies:
  pinenacl: ^0.5.1
  crypto: ^3.0.2

dev_dependencies:
  test: ^1.22.2
#  dependency_validator: ^3.2.2
  convert: ^3.1.1
